### ISSUE TITLE
Develop build and release process

### ISSUE THREAD

**Issue by nibtime** [iacm-med/shared#1]
### Tasks
* [x] add an src folder with dummy content to project
* [x] define build and watch tasks for all packages (Bili)
* [x] figure out best TS compiler options (in conjunction with Bili/Babel) 
* [x] try and error testing of the release process with Lerna
* [x] figure out branching model and release strategy
* [ ] try out TSDX as an alternative to Bili

### Questions
* Should we publish npm packages to npm main registry or to the GitHub npm registry of @iacm-med
