### ISSUE TITLE
Setup CI for build and release process

### ISSUE THREAD

**Issue by nibtime** [iacm-med/shared#2]
### Tasks
* [ ] get familiar with GitHub Actions and Workflows
* [ ] set up automated checks for PRs into master (prereleases)
* [ ] write GitHub Workflows that run packages publications (prerelease workflow on the `master` branch, stable release workflow on the `latest` branch)
